#############################################################################
# Makefile for building: APC
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  APC.pro
# Template: subdirs
# Command: C:\Qt\Qt5.8.0MGW\5.8\mingw53_32\bin\qmake.exe -o Makefile APC.pro -spec win32-g++
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\Qt5.8.0MGW\5.8\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src-APCDraw-pro \
		sub-src-APCRun-pro


sub-src-APCDraw-pro-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++
	cd src\ && $(MAKE) -f Makefile.APCDraw qmake_all
sub-src-APCDraw-pro: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw
sub-src-APCDraw-pro-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw 
sub-src-APCDraw-pro-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw all
sub-src-APCDraw-pro-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw clean
sub-src-APCDraw-pro-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw distclean
sub-src-APCDraw-pro-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw install
sub-src-APCDraw-pro-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw uninstall
sub-src-APCRun-pro-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++
	cd src\ && $(MAKE) -f Makefile.APCRun qmake_all
sub-src-APCRun-pro: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun
sub-src-APCRun-pro-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun 
sub-src-APCRun-pro-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun all
sub-src-APCRun-pro-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun clean
sub-src-APCRun-pro-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun distclean
sub-src-APCRun-pro-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun install
sub-src-APCRun-pro-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun uninstall

Makefile: APC.pro ../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf ../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/spec_pre.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/qdevice.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/device_config.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/common/angle.conf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/qconfig.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xlsx.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xlsx_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/qt_functions.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/qt_config.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/spec_post.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/toolchain.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/default_pre.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/resolve_config.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/default_post.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/win32/rtti.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/precompile_header.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/warn_on.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/qmake_use.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/file_copies.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/win32/windows.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/testcase_targets.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/exceptions.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/yacc.prf \
		../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/lex.prf \
		APC.pro
	$(QMAKE) -o Makefile APC.pro -spec win32-g++
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/spec_pre.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/qdevice.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/device_config.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/common/angle.conf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/qconfig.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xlsx.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xlsx_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/qt_functions.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/qt_config.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/spec_post.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/toolchain.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/default_pre.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/resolve_config.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/default_post.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/win32/rtti.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/precompile_header.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/warn_on.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/qmake_use.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/file_copies.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/win32/windows.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/testcase_targets.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/exceptions.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/yacc.prf:
../../Qt/Qt5.8.0MGW/5.8/mingw53_32/mkspecs/features/lex.prf:
APC.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile APC.pro -spec win32-g++

qmake_all: sub-src-APCDraw-pro-qmake_all sub-src-APCRun-pro-qmake_all FORCE

make_first: sub-src-APCDraw-pro-make_first sub-src-APCRun-pro-make_first  FORCE
all: sub-src-APCDraw-pro-all sub-src-APCRun-pro-all  FORCE
clean: sub-src-APCDraw-pro-clean sub-src-APCRun-pro-clean  FORCE
distclean: sub-src-APCDraw-pro-distclean sub-src-APCRun-pro-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-src-APCDraw-pro-install_subtargets sub-src-APCRun-pro-install_subtargets FORCE
uninstall_subtargets: sub-src-APCDraw-pro-uninstall_subtargets sub-src-APCRun-pro-uninstall_subtargets FORCE

sub-src-APCDraw-pro-debug:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw debug
sub-src-APCRun-pro-debug:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun debug
debug: sub-src-APCDraw-pro-debug sub-src-APCRun-pro-debug

sub-src-APCDraw-pro-release:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw release
sub-src-APCRun-pro-release:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun release
release: sub-src-APCDraw-pro-release sub-src-APCRun-pro-release

sub-src-APCDraw-pro-check:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw check
sub-src-APCRun-pro-check:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun check
check: sub-src-APCDraw-pro-check sub-src-APCRun-pro-check

sub-src-APCDraw-pro-benchmark:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCDraw $(QMAKE) -o Makefile.APCDraw C:\APP\APCDraw\src\APCDraw.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCDraw benchmark
sub-src-APCRun-pro-benchmark:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile.APCRun $(QMAKE) -o Makefile.APCRun C:\APP\APCDraw\src\APCRun.pro -spec win32-g++ ) && $(MAKE) -f Makefile.APCRun benchmark
benchmark: sub-src-APCDraw-pro-benchmark sub-src-APCRun-pro-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

